config/routes.rb
Dokno::Engine.routes.draw do
  resources :categories, except: [:show]
  resources :articles

  get '/(:cat_code)',          to: 'categories#index',     as: :article_index
  get '/up_for_review',        to: 'categories#index',     as: :up_for_review
  get 'article_panel/(:slug)', to: 'articles#panel',       as: :panel
  post 'article_preview',      to: 'articles#preview',     as: :preview
  post 'article_status',       to: 'articles#status',      as: :status
  root 'categories#index'
end

app/views/partials/_category_header.html.erb
<div class="no-print flex items-center mb-10">
  <% if Dokno::Category.exists? %>
    <div class="w-1/2 pr-5">
      <select aria-label="Category" name="category" id="category" size="1" class="rounded text-xl shadow-inner bg-gray-100 p-2 w-full max-w-full" onchange="applyCategoryCriteria(this.value, elem('#search_term').value, '<%= @order %>');">
        <option value="">Uncategorized</option>

        <optgroup label="Categories">
          <% cache Dokno::Category do %>
            <%= Dokno::Category.select_option_markup.html_safe %>
          <% end %>
        </optgroup>
      </select>
    </div>

    <script>
      // Client-side select of cached select list
      selectOption('category', '<%= j @category&.code %>');
    </script>
  <% end %>

  <% if Dokno::Article.exists? %>
    <div class="relative w-<%= Dokno::Category.exists? ? '1/2 pl-5' : 'full' %>">
      <i data-feather="search" class="absolute ml-4 mt-3 inline-block text-gray-300" title="Search"></i>
      <input title="Press / to search" onsearch="applyCategoryCriteria('<%= @category&.code %>', this.value, '<%= @order %>');" onfocus="disableSearchHotkey();" onblur="enableSearchHotkey();" placeholder="Search<%= @category.present? ? ' under this category' : ', hotkey /' %>" type="search" name="search_term" id="search_term" value="<%= @search_term %>" class="pl-12 pr-8 py-2 rounded text-xl shadow-inner bg-gray-100 w-full" />
      <% if @category.present? %><div title="Press / to search" class="absolute -ml-6 mt-2 inline-block text-gray-300 font-semibold">/</div><% end %>
    </div>
  <% end %>
</div>

<script> enableSearchHotkey(); </script>

app/views/partials/_form_errors.html.erb
<div id="error_explanation" class="bg-white mb-10">
  <h2 class="font-semibold">
    There
    <% if errors.count == 1 %>
      is a problem
    <% else %>
      are <%= pluralize(errors.count, "problem") %>
    <% end %>
    that must be resolved before saving:
  </h2>

  <ul class="mt-5 list-disc list-inside bg-gray-100 p-5 rounded">
    <% errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/partials/_logs.html.erb
<% if article&.logs.present? %>
  <div class="py-10 px-16 text-gray-200 bg-gray-900">
    <div class="w-full max-w-screen-xl m-auto">
      <div class="text-xl text-gray-600 cursor-pointer" onclick="toggleVisibility('change-log');">
        Change history for this article

        <div class="inline toggle-visibility-indicator-container change-log">
          <i data-feather="chevron-left" class="inline toggle-visibility-indicator change-log"></i>
        </div>
      </div>

      <div id="change-log" class="bg-gray-800 px-10 mt-8 rounded hidden text-gray-500">
        <ul>
          <% article.logs.includes(article: :categories).each do |log| %>
            <li class="my-10">
              <div>
                <% if article.blank? %>
                  <div class="text-white text-xl"><a href="<%= article_path log.article.slug %>" title="View Article"><%= log.article.title %></a></div>
                  <div class="mb-5"><%= log.article.category_name_list %></div>
                <% end %>

                <div class="text-gray-500 bg-gray-700 p-5 pr-10 rounded <%= 'cursor-pointer' if log.diff_left != log.diff_right %> flex items-center" onclick="toggleVisibility('article-diff-<%= log.id %>');" title="Show / Hide Diff">
                  <div class="w-<%= log.diff_left != log.diff_right ? '11/12' : 'full' %>">
                    <%= time_ago_in_words log.created_at %> ago
                    <% if log.username.present? %>
                      by <%= log.username %>
                    <% end %>

                    <% if log.meta.present? %>
                      <br /><span class="text-gray-300"><%= log.meta %></span>
                    <% end %>
                  </div>

                  <% if log.diff_left != log.diff_right %>
                    <div class="w-1/12 text-right toggle-visibility-indicator-container article-diff-<%= log.id %>">
                      <i data-feather="chevron-left" class="inline toggle-visibility-indicator article-diff-<%= log.id %>"></i>
                    </div>
                  <% end %>
                </div>

                <% if log.diff_left != log.diff_right %>
                  <div id="article-diff-<%= log.id %>" class="flex hidden">
                    <div class="w-1/2 p-5">Before:<br /><%= log.diff_left.html_safe %></div>
                    <div class="w-1/2 p-5">After:<br /><%= log.diff_right.html_safe %></div>
                  </div>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/partials/_pagination.html.erb
<% if @total_pages > 1 %>
  <span class="mr-5">
    <% if @page > 1 %>
      <span class="mr-1 inline-block"><a href="?search_term=<%= CGI.escape @search_term.to_s %>&order=<%= @order %>&page=<%= (@page - 1) %>"><i data-feather="arrow-left" class="h-5 inline-block" title="Previous page"></i></a></span>
    <% end %>

    <span class="mr-1 inline-block">Page</span>

    <%= form_with(url: article_index_path(@category&.code), method: :get, class: 'inline') do %>
      <input type="hidden" name="search_term" value="<%= @search_term %>">
      <input type="hidden" name="order" value="<%= @order %>">
      <input aria-label="Page" type="text" name="page" value="<%= @page %>" onclick="this.select();" class="w-10 text-center bg-gray-200 rounded" />

      <span class="mx-1 inline-block">of</span>
      <span class="text-center inline-block"><%= @total_pages %></span>
    <% end %>

    <% if @page < @total_pages %>
      <span class="ml-1 inline-block"><a href="?search_term=<%= CGI.escape @search_term.to_s %>&order=<%= @order %>&page=<%= (@page + 1) %>"><i data-feather="arrow-right" class="h-5 inline-block" title="Next page"></i></a></span>
    <% end %>
  </span>
<% end %>

<span class="text-gray-400">
  <%= @total_records %>
  <%= 'uncategorized' if !current_page?(up_for_review_path) && @category.blank? && @search_term.blank? %>
  <%= 'article'.pluralize(@total_records) %>
  <%= 'up for review' if current_page?(up_for_review_path) %>

  <% if @search_term.present? %>
    containing <span class="font-serif">&ldquo;</span><%= @search_term %><span class="font-serif">&rdquo;</span>
  <% end %>

  <% if @category.present? %>
    in <%= "#{(children_count = @category.branch.count) == 1 ? 'this' : children_count} #{'category'.pluralize(children_count)}" %>
  <% end %>
</span>