config/routes.rb
Dokno::Engine.routes.draw do
  resources :categories, except: [:show]
  resources :articles

  get '/(:cat_code)',          to: 'categories#index',     as: :article_index
  get '/up_for_review',        to: 'categories#index',     as: :up_for_review
  get 'article_panel/(:slug)', to: 'articles#panel',       as: :panel
  post 'article_preview',      to: 'articles#preview',     as: :preview
  post 'article_status',       to: 'articles#status',      as: :status
  root 'categories#index'
end

app/models/dokno/application_record.rb
module Dokno
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    include Engine.routes.url_helpers
    include ActionView::Helpers::DateHelper
  end
end

app/models/dokno/article_slug.rb
module Dokno
  class ArticleSlug < ApplicationRecord
    belongs_to :article

    validates :slug, presence: true
  end
end

app/models/dokno/category.rb
module Dokno
  class Category < ApplicationRecord
    belongs_to :parent, class_name: 'Dokno::Category', primary_key: 'id', foreign_key: 'category_id', inverse_of: :children, optional: true
    has_many :children, class_name: 'Dokno::Category', primary_key: 'id', foreign_key: 'category_id', inverse_of: :parent, dependent: :nullify

    has_and_belongs_to_many :articles

    before_validation :set_code
    validates :name, :code, presence: true, uniqueness: true
    validate :circular_parent_check

    scope :alpha_order, -> { order(:name) }

    def breadcrumb(**args)
      crumbs = [(category_link(self, args) unless args[:hide_self])]
      parent_category_id = category_id

      loop do
        break if parent_category_id.blank?

        parent_category = Category.find(parent_category_id)
        crumbs.prepend category_link(parent_category, args)
        parent_category_id = parent_category.category_id
      end

      crumbs.compact.join("&nbsp;&nbsp;>&nbsp;&nbsp;").html_safe
    end

    def category_link(category, args={})
      %(<a href="#{article_index_path(category.code)}?search_term=#{CGI.escape(args[:search_term].to_s)}&order=#{CGI.escape(args[:order].to_s)}">#{category.name}</a>)
    end

    # All Articles in the Category, including all child Categories
    def articles_in_branch(order: :updated)
      records = Article
        .includes(:categories_dokno_articles, :categories)
        .joins(:categories)
        .where(dokno_categories: { id: self.class.branch(parent_category_id: id).pluck(:id) })

      Article.apply_sort(records, order: order)
    end

    def branch
      self.class.branch(parent_category_id: id)
    end

    # Used to invalidate the fragment cache of the hierarchical category select options
    def self.cache_key
      [maximum(:updated_at), Article.maximum(:updated_at)].compact.max
    end

    # The given Category and all child Categories. Useful for filtering associated articles.
    def self.branch(parent_category_id:, at_top: true)
      return if parent_category_id.blank?

      categories = []
      parent_category = find(parent_category_id)
      child_categories = parent_category.children.to_a

      child_categories.each do |child_category|
        categories << child_category << branch(parent_category_id: child_category.id, at_top: false)
      end

      categories.prepend parent_category if at_top
      categories.flatten
    end

    def self.select_option_markup(selected_category_codes: nil, context_category: nil, level: 0)
      return '' if level.positive? && context_category.blank?

      options = []
      level_categories = where(category_id: context_category&.id).alpha_order
      level_categories.each do |category|
        options << option_markup(category: category, selected_category_codes: selected_category_codes, level: level)
        options << select_option_markup(selected_category_codes: selected_category_codes, context_category: category, level: (level + 1))
      end

      options.join
    end

    private

    def self.option_markup(category:, selected_category_codes:, level: 0)
      selected = selected_category_codes&.include?(category.code)
      article_count = category.articles_in_branch.size
      %(<option value="#{category.code}" #{'selected="selected"' if selected}>#{('&nbsp;&nbsp;' * level)}#{category.name}#{' (' + article_count.to_s + ')' if article_count.positive?}</option>)
    end

    # Never allow setting of parent to self
    def circular_parent_check
      return unless persisted? && id.to_i == category_id.to_i

      errors.add(:category_id, "can't set parent to self")
    end

    def set_code
      return unless name.present?

      self.code = name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
    end
  end
end

app/models/dokno/log.rb
module Dokno
  class Log < ApplicationRecord
    belongs_to :article

    default_scope { order(created_at: :desc) }
  end
end

app/controllers/dokno/application_controller.rb
module Dokno
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception

    include UserConcern
    include PaginationConcern

    add_flash_types :green, :yellow, :red, :gray
  end
end

app/controllers/dokno/articles_controller.rb
require_dependency 'dokno/application_controller'

module Dokno
  class ArticlesController < ApplicationController
    before_action :authorize,     except: [:show, :panel]
    before_action :fetch_article, only: [:show, :edit, :panel, :status]
    before_action :update_views,  only: [:show]

    def show
      redirect_to root_path if @article.blank?

      @search_term = params[:search_term]
      @order       = params[:order]
      @category    = Category.find_by(code: params[:cat_code].to_s.strip) if params[:cat_code].present?
      @category    = @article.categories.first if @category.blank?

      if !@article.active
        flash.now[:yellow] = 'This article is no longer active'
      elsif @article.up_for_review?
        flash_msg = @article.review_due_days_string
        flash_msg += " - <a href='#{edit_article_path(@article.slug)}' class='font-bold'>review it now</a>" if can_edit?
        flash.now[:gray] = flash_msg
      end
    end

    def new
      @article        = Article.new
      @template       = Article.template
      @category_codes = [] << params[:category_code]
    end

    def edit
      return redirect_to root_path if @article.blank?
      @category_codes = @article.categories.pluck(:code)
    end

    def create
      @article = Article.new(article_params)
      set_editor_username

      if @article.save
        flash[:green]       = 'Article was created'
        @article.categories = Category.where(code: params[:category_code]) if params[:category_code].present?
        redirect_to article_path @article.slug
      else
        flash.now[:red] = 'Article could not be created'
        @category_codes = params[:category_code]
        render :new
      end
    end

    def update
      @article = Article.find_by(id: params[:id].to_i)
      return redirect_to root_path if @article.blank?

      set_editor_username

      if @article.update(article_params)
        flash[:green]       = 'Article was updated'
        @article.categories = Category.where(code: params[:category_code])
        redirect_to article_path @article.slug
      else
        flash.now[:red]     = 'Article could not be updated'
        @category_codes     = params[:category_code]
        @reset_review_date  = params[:reset_review_date]
        @review_notes       = params[:review_notes]
        render :edit
      end
    end

    def destroy
      Article.find(params[:id].to_i).destroy!

      flash[:green] = 'Article was deleted'
      render json: {}, layout: false
    end

    # Ajax-fetched slide-in article panel for the host app
    def panel
      render json: @article&.host_panel_hash, layout: false
    end

    # Ajax-fetched preview of article content from article form
    def preview
      content = Article.parse_markdown params['markdown']
      render json: { parsed_content: content.presence || 'Nothing to preview' }, layout: false
    end

    # Ajax-invoked article status changing
    def status
      set_editor_username
      @article.update!(active: params[:active])
      render json: {}, layout: false
    end

    private

    def article_params
      params.permit(:slug, :title, :summary, :markdown, :reset_review_date, :review_notes, :starred)
    end

    def fetch_article
      # Find by slug
      slug = (params[:slug].presence || params[:id]).to_s.strip
      @article = Article.find_by(slug: slug)
      return if @article.present?

      # Find by an old slug that has been changed (redirect to current slug)
      old_slug = ArticleSlug.find_by(slug: slug)
      return redirect_to article_path(old_slug.article.slug) if old_slug.present?

      # Find by ID (redirect to slug)
      article = Article.find_by(id: params[:id].to_i)
      return redirect_to article_path(article.slug) if article.present?
    end

    def set_editor_username
      @article&.editor_username = username
    end

    def update_views
      return unless @article.present?
      return unless (@article.last_viewed_at || 2.minutes.ago) < 1.minute.ago

      # No callbacks here, intentionally
      @article.update_columns(views: (@article.views + 1), last_viewed_at: Time.now.utc)
    end
  end
end

app/controllers/dokno/categories_controller.rb
require_dependency 'dokno/application_controller'

module Dokno
  class CategoriesController < ApplicationController
    before_action :authorize,      except: [:index]
    before_action :fetch_category, only: [:index, :edit, :update]

    def index
      @search_term        = params[:search_term]
      @order              = params[:order]&.strip
      @order              = 'updated' unless %w(updated newest views alpha).include?(@order)
      @show_up_for_review = can_edit? && !request.path.include?(up_for_review_path)

      articles = if request.path.include? up_for_review_path
                   Article.up_for_review(order: @order&.to_sym)
                 elsif @search_term.present?
                   Article.search(term: @search_term, category_id: @category&.id, order: @order&.to_sym)
                 elsif @category.present?
                   @category.articles_in_branch(order: @order&.to_sym)
                 else
                   Article.uncategorized(order: @order&.to_sym)
                 end

      @articles = paginate(articles)
    end

    def new
      @category             = Category.new
      @parent_category_code = params[:parent_category_code]
    end

    def edit
      return redirect_to root_path if @category.blank?
      @parent_category_code = @category.parent&.code
    end

    def create
      @category = Category.new(name: params[:name], parent: Category.find_by(code: params[:parent_category_code]))

      if @category.save
        flash[:green] = 'Category was created'
        redirect_to article_index_path(@category.code)
      else
        flash.now[:red]       = 'Category could not be created'
        @parent_category_code = params[:parent_category_code]
        render :new
      end
    end

    def update
      return redirect_to root_path if @category.blank?

      if @category.update(name: params[:name], parent: Category.find_by(code: params[:parent_category_code]))
        flash[:green] = 'Category was updated'
        redirect_to article_index_path(@category.code)
      else
        flash.now[:red]       = 'Category could not be updated'
        @parent_category_code = params[:parent_category_code]
        render :edit
      end
    end

    def destroy
      Category.find(params[:id].to_i).destroy!

      flash[:green] = 'Category was deleted'
      render json: {}, layout: false
    end

    private

    def fetch_category
      @category = Category.find_by(code: params[:cat_code].to_s.strip)
      @category = Category.find_by(id: params[:id].to_i) if @category.blank?
    end
  end
end

app/controllers/dokno/pagination_concern.rb
module Dokno
  module PaginationConcern
    extend ActiveSupport::Concern

    def paginate(records, max_per_page: 10)
      @page          = params[:page].to_i
      @total_records = records.size
      @total_pages   = (@total_records.to_f / max_per_page).ceil
      @total_pages   = 1 unless @total_pages.positive?
      @page          = 1 unless @page.positive? && @page <= @total_pages

      records.offset((@page - 1) * max_per_page).limit(max_per_page)
    end
  end
end

app/controllers/dokno/user_concern.rb
module Dokno
  module UserConcern
    extend ActiveSupport::Concern

    included do
      helper_method :user, :username, :can_edit?
    end

    def user
      # Attempt to eval the currently signed in 'user' object from the host app
      proc {
        $safe = 1
        eval sanitized_user_obj_string
      }.call

    rescue NameError => _e
      nil
    end

    def sanitized_user_obj_string
      Dokno.config.app_user_object.to_s.split(/\b/).first
    end

    def username
      user&.send(Dokno.config.app_user_name_method.to_sym).to_s
    end

    def can_edit?
      # Allow editing by default if host app user object is not configured
      return true  unless sanitized_user_obj_string.present?
      return false unless user&.respond_to? Dokno.config.app_user_auth_method.to_sym

      user.send(Dokno.config.app_user_auth_method.to_sym)
    end

    def authorize
      return redirect_to root_path unless can_edit?
    end
  end
end

app/helpers/dokno/application_helper.rb
module Dokno
  module ApplicationHelper
    def dokno_article_link(link_text = nil, slug: nil)
      return "Dokno article slug is required" unless slug.present?

      # Check for slug, including deprecated slugs
      article = Article.find_by(slug: slug.strip)
      article = ArticleSlug.find_by(slug: slug.strip)&.article if article.blank?

      return "Dokno article slug '#{slug}' not found" if article.blank?

      %Q(<a class="dokno-link" href="javascript:;" onclick="doknoOpenPanel('#{j article.slug}');">#{link_text.presence || article.title}</a>).html_safe
    end
  end
end

app/views/dokno/articles/_article_form.html.erb
<%= render 'dokno/article_formatting' %>

<section class="mb-10">

  <div class="text-2xl mb-5 text-gray-500"><%= article.persisted? ? 'Edit' : 'New' %> Article</div>
  <h1 class="text-4xl leading-tight font-light"><%= article.title %></h1>
  <hr class="mt-8 mb-10" />

  <% if article.up_for_review? %>
    <div class="bg-gray-800 text-gray-100 rounded mb-10">
      <h2 class="bg-gray-900 p-10 rounded-t text-2xl leading-tight font-light">Review for Accuracy / Relevance</h2>

      <div class="flex p-10">
        <div class="w-1/2 pr-5">
          <div>
            <span class="text-lg font-semibold"><label for="reset_review_date">Reset the next review date?</label></span>
            <input onchange="setReviewForm();" type="checkbox" name="reset_review_date" id="reset_review_date" value="true" class="ml-2 text-lg" <%= "checked='checked'" if @reset_review_date %> />
          </div>
          <div class="text-gray-400">
            <%= article.review_due_days_string %>.
            Check the box above to mark this article as reviewed and reset the next review date to <span class="px-2 py-1 bg-gray-900 rounded text-white font-semibold"><%= "#{Date.today + Dokno.config.article_review_period}" %></span>
          </div>
        </div>
        <div class="w-1/2">
          <div class="text-lg font-semibold"><label for="review_notes">Reviewer Notes</label></div>
          <textarea placeholder="Any review notes here will be added to the change history for this article" name="review_notes" id="review_notes" class="rounded text-xl shadow-inner bg-gray-100 p-3 mt-2 w-full text-gray-900" rows="2"><%= @review_notes %></textarea>
        </div>
      </div>
    </div>
  <% end %>

  <div class="mb-5">
    <div class="text-lg font-semibold"><label for="slug">Slug</label></div>
    <input placeholder="Article unique identifier" type="text" name="slug" id="slug" value="<%= article.slug %>" class="rounded text-xl shadow-inner bg-gray-100 p-2 mt-2 w-1/3" />
    <div class="text-gray-500 mt-2">Unique identifier for this article (required) (2-20 alphanumeric chars)</div>
  </div>

  <% if Dokno::Category.exists? %>
    <div class="mb-5 w-2/3">
      <div class="text-lg font-semibold"><label for="category_code"><%= 'Category'.pluralize article.categories.count %></label></div>
      <select name="category_code[]" id="category_code" multiple="multiple" size="<%= (cat_count = Dokno::Category.count) <= 9 ? (cat_count + 1).to_s : '10' %>" class="rounded text-xl shadow-inner bg-gray-100 p-2 w-full mt-2 w-full max-w-full">
        <option></option>
        <%= Dokno::Category.select_option_markup(selected_category_codes: @category_codes).html_safe %>
      </select>
      <div class="text-gray-500 mt-2">
        If applicable, select one or more categories to which this article will belong (optional). CTRL/CMD to select multiple.
        Articles will be automatically included in parent categories. Uncategorized articles
        are displayed on the landing page.
      </div>
    </div>
  <% end %>

  <hr class="my-10" />

  <div class="mb-5">
    <div class="text-lg font-semibold"><label for="title">Title</label></div>
    <input placeholder="Article title" type="text" name="title" id="title" value="<%= article.title %>" class="rounded text-xl shadow-inner bg-gray-100 p-2 mt-2 w-1/2" />
    <div class="text-gray-500 mt-2">Descriptive article title (required) (5-255 alphanumeric chars)</div>
  </div>

  <div class="mb-5">
    <div class="text-lg font-semibold"><label for="summary">Summary</label></div>
    <input placeholder="Brief article summary" type="text" name="summary" id="summary" value="<%= article.summary %>" class="rounded text-xl shadow-inner bg-gray-100 p-2 mt-2 w-full" />
    <div class="text-gray-500 mt-2">Brief summary of the described topic (text only)</div>
  </div>

  <div class="mb-5">
    <div class="text-lg font-semibold">
      <label for="markdown">Content</label>
      <a id="markdown_write_link" href="javascript:;" onclick="writeArticleToggle();" class="float-right hidden"><i data-feather="pen-tool" class="inline"></i> Write</a>
      <a id="markdown_preview_link" href="javascript:;" onclick="previewArticleToggle();" class="float-right"><i data-feather="eye" class="inline"></i> Preview</a>
    </div>
    <textarea placeholder="Full article content" name="markdown" id="markdown" class="rounded text-xl shadow-inner bg-gray-100 p-3 mt-2 w-full" rows="20"><%= article.persisted? ? article.markdown : (article.markdown.presence || @template) %></textarea>
    <div id="markdown_preview" class="dokno-article-content-markup hidden text-lg overflow-hidden overflow-y-auto rounded p-10 mt-2 bg-gray-100 shadow-inner"></div>
    <div class="text-gray-500 mt-2">Detailed documentation of the described topic. Basic HTML &amp; <a target="_blank" href="https://commonmark.org/help/" title="Markdown formatting examples">markdown</a> OK.</div>
  </div>

  <div class="mb-5">
    <div>
      <span class="text-lg font-semibold"><label for="starred">Starred article?</label></span>
      <input type="hidden" name="starred" value="false" />
      <input type="checkbox" name="starred" id="starred" value="true" class="ml-2 text-lg" <%= "checked='checked'" if article.starred %> />
    </div>
    <div class="text-gray-400">
      Starred articles are always listed first when browsing.
    </div>
  </div>

  <hr class="my-10" />

  <div class="text-right">
    <span class="text-lg mr-5"><a class="no-underline" href="<%= article.persisted? ? article_path(article.slug) : root_path %>">Cancel</a></span>
    <button type="submit" class="bg-gray-700 text-gray-300 hover:bg-gray-900 hover:text-white rounded py-2 px-3 font-bold"><i data-feather="check" class="inline h-5"></i> SAVE ARTICLE</button>
  </div>

</section>

<script>
  elem('input#slug').focus();
  setReviewForm();
</script>

app/views/dokno/articles/edit.html.erb
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any? %>
    <%= render 'partials/form_errors', errors: @article.errors %>
  <% end %>

  <%= render 'article_form', article: @article %>
<% end %>

app/views/dokno/articles/new.html.erb
<%= form_with(url: articles_path) do %>
  <% if @article.errors.any? %>
    <%= render 'partials/form_errors', errors: @article.errors %>
  <% end %>
  
  <%= render 'article_form', article: @article %>
<% end %>

app/views/dokno/articles/show.html.erb
<%= render 'dokno/article_formatting' %>

<% if @category.present? %>
  <div class="no-print text-gray-500 mb-5">
    <div>
      <% if request.referrer&.include? article_index_path %>
        <a class="fixed left-0 ml-6" title="Back" href="javascript:history.back();"><i data-feather="chevrons-left" class="text-gray-300 h-5 align-text-bottom inline"></i></a>
      <% end %>
      <span class="text-gray-500 mr-1">Under</span> <%= @category.breadcrumb(search_term: @search_term, order: @order) %>
    </div>
  </div>
<% end %>

<%= render 'partials/category_header' %>

<div class="my-10 no-print"><hr /></div>

<section>
  <div class="flex">
    <div id="dokno-article-sidebar" class="w-2/5 pr-10">
      <h1 class="dokno-article-content-highlight text-4xl mb-8 leading-tight font-light">
        <%= @article.title %>
        <% if @article.starred %><i title="Starred article" data-feather="star" class="inline align-middle"></i><% end %>
      </h1>

      <div>
        <div class="mb-8 no-print">
          <button title="Copy link" class="bg-gray-600 text-gray-300 hover:text-white rounded my-2 mr-2 py-2 px-3 font-bold text-sm" onclick="copyToClipboard('<%= @article.permalink(request.base_url) %>');"><i data-feather="clipboard" class="inline h-5"></i> COPY</button>
          <button title="Email article" class="bg-gray-600 text-gray-300 hover:text-white rounded my-2 mr-2 py-2 px-3 font-bold text-sm" onclick="window.open('mailto:?subject=<%= CGI.escape(@article.title.to_s) %>&body=<%= CGI.escape(article_url(@article.slug)) %>');"><i data-feather="send" class="inline h-5"></i> EMAIL</button>
          <button title="Print article" class="bg-gray-600 text-gray-300 hover:text-white rounded my-2 py-2 px-3 font-bold text-sm" onclick="window.print();"><i data-feather="printer" class="inline h-5"></i> PRINT</button>
        </div>

        <div class="flex">
          <div class="no-print w-8"><i data-feather="clock" class="inline-block h-5 mr-2"></i></div>
          <div class="w-full">
            Last updated:<br />
            <%= time_ago_in_words @article.updated_at %> ago
            <% if (editor_username = @article.logs.first&.username).present? %>
              by <%= editor_username %>
            <% end %>
          </div>
        </div>

        <div class="mt-5 flex no-print">
          <div class="no-print w-8"><i data-feather="eye" class="inline-block h-5 mr-2"></i></div>
          <div class="w-full">
            Views:<br />
            <%= number_with_delimiter(@article.views, delimiter: ',') %>
          </div>
        </div>

        <% if @article.contributors.present? %>
          <div class="mt-5 flex">
            <div class="no-print w-8"><i data-feather="user-check" class="inline-block h-5 mr-2"></i></div>
            <div class="w-full">
              Contributors:<br />
              <%= @article.contributors %>
            </div>
          </div>
        <% end %>

        <% if @article.reading_time.present? %>
          <div class="mt-5 flex no-print">
            <div class="no-print w-8"><i data-feather="watch" class="inline-block h-5 mr-2"></i></div>
            <div class="w-full">
              Reading time:<br />
              <%= @article.reading_time %>
            </div>
          </div>
        <% end %>

        <div class="mt-5 flex">
          <div class="no-print w-8"><i data-feather="link" class="inline-block h-5 mr-2"></i></div>
          <div class="w-full">
            Permalink:<br />
            <a class="inline-block mt-1 -ml-2 px-2 py-1 bg-blue-100 rounded" title="Copy to clipboard" href="javascript:;" onclick="copyToClipboard('<%= @article.permalink(request.base_url) %>');"><%= @article.permalink(request.base_url) %></a>
          </div>
        </div>

        <% if can_edit? %>
          <div class="mt-5 flex no-print">
            <div class="no-print w-8"><i data-feather="crosshair" class="inline-block h-5 mr-2"></i></div>
            <div class="w-full">
              Unique slug:<br />
              <a class="inline-block mt-1 -ml-2 px-2 py-1 bg-blue-100 rounded" title="Copy to clipboard" href="javascript:;" onclick="copyToClipboard('<%= j @article.slug %>');"><%= @article.slug %></a>

              <% if (old_slugs = @article.article_slugs).present? %>
                <div class="text-gray-500 mt-5">
                  Editor note:<br />
                  This article is still accessible via previous
                  <%= 'slug'.pluralize(old_slugs.count) %>
                  <%= old_slugs.map(&:slug).reject { |slug| slug == @article.slug }.to_sentence %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>

        <% if (category_name_list = @article.category_name_list(context_category_id: @category&.id)).present? %>
          <div class="mt-5 flex no-print">
            <div class="no-print w-8"><i data-feather="folder" class="inline-block h-5 mr-2"></i></div>
            <div class="w-full">
              <%= category_name_list.sub(':', ':<br />').html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div id="dokno-article-content" class="dokno-article-content-highlight w-3/5">
      <% if @article.summary.present? %>
        <div class="text-2xl mb-8 text-gray-700 font-light"><%= simple_format @article.summary %></div>
      <% end %>

      <% if @article.markdown.present? %>
        <div id="dokno-article-content-markup" class="dokno-article-content-markup text-gray-800 font-light mb-10 bg-gray-100 p-10 rounded">
          <%= @article.markdown_parsed %>
        </div>
      <% end %>

      <% if @article.summary.blank? && @article.markdown.blank? %>
        <div class="mb-10">No content</div>
      <% end %>
    </div>
  </div>
</section>

<% if can_edit? %>
  <div class="no-print">
    <hr class="mt-5 mb-10" />
    <div class="text-right">
      <button title="Edit article" class="bg-blue-900 text-gray-300 hover:text-white rounded mr-5 py-2 px-3 font-bold text-sm" onclick="location.href='<%= edit_article_path(@article.slug) %>';"><i data-feather="edit-2" class="inline h-5"></i> EDIT</button>

      <% if @article.active %>
        <button title="Deactivate article" id="article-deactivate-button" class="bg-yellow-700 text-gray-300 hover:text-white rounded mr-5 py-2 px-3 font-bold text-base" onclick="setArticleStatus('<%= @article.slug %>', false);"><i data-feather="file-minus" class="inline h-5"></i> DEACTIVATE</button>
      <% else %>
        <button title="Re-activate article" id="article-activate-button" class="bg-green-700 text-gray-300 hover:text-white rounded mr-5 py-2 px-3 font-bold text-base" onclick="setArticleStatus('<%= @article.slug %>', true);"><i data-feather="file-plus" class="inline h-5"></i> RE-ACTIVATE</button>
      <% end %>
      <button title="Permanently delete article" class="bg-red-700 text-gray-300 hover:text-white rounded py-2 px-3 font-bold text-base" onclick="deleteArticle('<%= @article.id %>');"><i data-feather="slash" class="inline h-5"></i> DELETE</button>
    </div>
  </div>
<% end %>