config/routes.rb
Dokno::Engine.routes.draw do
  resources :categories, except: [:show]
  resources :articles

  get '/(:cat_code)',          to: 'categories#index',     as: :article_index
  get '/up_for_review',        to: 'categories#index',     as: :up_for_review
  get 'article_panel/(:slug)', to: 'articles#panel',       as: :panel
  post 'article_preview',      to: 'articles#preview',     as: :preview
  post 'article_status',       to: 'articles#status',      as: :status
  root 'categories#index'
end

app/models/dokno/application_record.rb
module Dokno
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    include Engine.routes.url_helpers
    include ActionView::Helpers::DateHelper
  end
end

app/models/dokno/article_slug.rb
module Dokno
  class ArticleSlug < ApplicationRecord
    belongs_to :article

    validates :slug, presence: true
  end
end

app/models/dokno/category.rb
module Dokno
  class Category < ApplicationRecord
    belongs_to :parent, class_name: 'Dokno::Category', primary_key: 'id', foreign_key: 'category_id', inverse_of: :children, optional: true
    has_many :children, class_name: 'Dokno::Category', primary_key: 'id', foreign_key: 'category_id', inverse_of: :parent, dependent: :nullify

    has_and_belongs_to_many :articles

    before_validation :set_code
    validates :name, :code, presence: true, uniqueness: true
    validate :circular_parent_check

    scope :alpha_order, -> { order(:name) }

    def breadcrumb(**args)
      crumbs = [(category_link(self, args) unless args[:hide_self])]
      parent_category_id = category_id

      loop do
        break if parent_category_id.blank?

        parent_category = Category.find(parent_category_id)
        crumbs.prepend category_link(parent_category, args)
        parent_category_id = parent_category.category_id
      end

      crumbs.compact.join("&nbsp;&nbsp;>&nbsp;&nbsp;").html_safe
    end

    def category_link(category, args={})
      %(<a href="#{article_index_path(category.code)}?search_term=#{CGI.escape(args[:search_term].to_s)}&order=#{CGI.escape(args[:order].to_s)}">#{category.name}</a>)
    end

    # All Articles in the Category, including all child Categories
    def articles_in_branch(order: :updated)
      records = Article
        .includes(:categories_dokno_articles, :categories)
        .joins(:categories)
        .where(dokno_categories: { id: self.class.branch(parent_category_id: id).pluck(:id) })

      Article.apply_sort(records, order: order)
    end

    def branch
      self.class.branch(parent_category_id: id)
    end

    # Used to invalidate the fragment cache of the hierarchical category select options
    def self.cache_key
      [maximum(:updated_at), Article.maximum(:updated_at)].compact.max
    end

    # The given Category and all child Categories. Useful for filtering associated articles.
    def self.branch(parent_category_id:, at_top: true)
      return if parent_category_id.blank?

      categories = []
      parent_category = find(parent_category_id)
      child_categories = parent_category.children.to_a

      child_categories.each do |child_category|
        categories << child_category << branch(parent_category_id: child_category.id, at_top: false)
      end

      categories.prepend parent_category if at_top
      categories.flatten
    end

    def self.select_option_markup(selected_category_codes: nil, context_category: nil, level: 0)
      return '' if level.positive? && context_category.blank?

      options = []
      level_categories = where(category_id: context_category&.id).alpha_order
      level_categories.each do |category|
        options << option_markup(category: category, selected_category_codes: selected_category_codes, level: level)
        options << select_option_markup(selected_category_codes: selected_category_codes, context_category: category, level: (level + 1))
      end

      options.join
    end

    private

    def self.option_markup(category:, selected_category_codes:, level: 0)
      selected = selected_category_codes&.include?(category.code)
      article_count = category.articles_in_branch.size
      %(<option value="#{category.code}" #{'selected="selected"' if selected}>#{('&nbsp;&nbsp;' * level)}#{category.name}#{' (' + article_count.to_s + ')' if article_count.positive?}</option>)
    end

    # Never allow setting of parent to self
    def circular_parent_check
      return unless persisted? && id.to_i == category_id.to_i

      errors.add(:category_id, "can't set parent to self")
    end

    def set_code
      return unless name.present?

      self.code = name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
    end
  end
end

app/models/dokno/log.rb
module Dokno
  class Log < ApplicationRecord
    belongs_to :article

    default_scope { order(created_at: :desc) }
  end
end

app/controllers/dokno/application_controller.rb
module Dokno
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception

    include UserConcern
    include PaginationConcern

    add_flash_types :green, :yellow, :red, :gray
  end
end

app/controllers/dokno/articles_controller.rb
require_dependency 'dokno/application_controller'

module Dokno
  class ArticlesController < ApplicationController
    before_action :authorize,     except: [:show, :panel]
    before_action :fetch_article, only: [:show, :edit, :panel, :status]
    before_action :update_views,  only: [:show]

    def show
      redirect_to root_path if @article.blank?

      @search_term = params[:search_term]
      @order       = params[:order]
      @category    = Category.find_by(code: params[:cat_code].to_s.strip) if params[:cat_code].present?
      @category    = @article.categories.first if @category.blank?

      if !@article.active
        flash.now[:yellow] = 'This article is no longer active'
      elsif @article.up_for_review?
        flash_msg = @article.review_due_days_string
        flash_msg += " - <a href='#{edit_article_path(@article.slug)}' class='font-bold'>review it now</a>" if can_edit?
        flash.now[:gray] = flash_msg
      end
    end

    def new
      @article        = Article.new
      @template       = Article.template
      @category_codes = [] << params[:category_code]
    end

    def edit
      return redirect_to root_path if @article.blank?
      @category_codes = @article.categories.pluck(:code)
    end

    def create
      @article = Article.new(article_params)
      set_editor_username

      if @article.save
        flash[:green]       = 'Article was created'
        @article.categories = Category.where(code: params[:category_code]) if params[:category_code].present?
        redirect_to article_path @article.slug
      else
        flash.now[:red] = 'Article could not be created'
        @category_codes = params[:category_code]
        render :new
      end
    end

    def update
      @article = Article.find_by(id: params[:id].to_i)
      return redirect_to root_path if @article.blank?

      set_editor_username

      if @article.update(article_params)
        flash[:green]       = 'Article was updated'
        @article.categories = Category.where(code: params[:category_code])
        redirect_to article_path @article.slug
      else
        flash.now[:red]     = 'Article could not be updated'
        @category_codes     = params[:category_code]
        @reset_review_date  = params[:reset_review_date]
        @review_notes       = params[:review_notes]
        render :edit
      end
    end

    def destroy
      Article.find(params[:id].to_i).destroy!

      flash[:green] = 'Article was deleted'
      render json: {}, layout: false
    end

    # Ajax-fetched slide-in article panel for the host app
    def panel
      render json: @article&.host_panel_hash, layout: false
    end

    # Ajax-fetched preview of article content from article form
    def preview
      content = Article.parse_markdown params['markdown']
      render json: { parsed_content: content.presence || 'Nothing to preview' }, layout: false
    end

    # Ajax-invoked article status changing
    def status
      set_editor_username
      @article.update!(active: params[:active])
      render json: {}, layout: false
    end

    private

    def article_params
      params.permit(:slug, :title, :summary, :markdown, :reset_review_date, :review_notes, :starred)
    end

    def fetch_article
      # Find by slug
      slug = (params[:slug].presence || params[:id]).to_s.strip
      @article = Article.find_by(slug: slug)
      return if @article.present?

      # Find by an old slug that has been changed (redirect to current slug)
      old_slug = ArticleSlug.find_by(slug: slug)
      return redirect_to article_path(old_slug.article.slug) if old_slug.present?

      # Find by ID (redirect to slug)
      article = Article.find_by(id: params[:id].to_i)
      return redirect_to article_path(article.slug) if article.present?
    end

    def set_editor_username
      @article&.editor_username = username
    end

    def update_views
      return unless @article.present?
      return unless (@article.last_viewed_at || 2.minutes.ago) < 1.minute.ago

      # No callbacks here, intentionally
      @article.update_columns(views: (@article.views + 1), last_viewed_at: Time.now.utc)
    end
  end
end

app/controllers/dokno/categories_controller.rb
require_dependency 'dokno/application_controller'

module Dokno
  class CategoriesController < ApplicationController
    before_action :authorize,      except: [:index]
    before_action :fetch_category, only: [:index, :edit, :update]

    def index
      @search_term        = params[:search_term]
      @order              = params[:order]&.strip
      @order              = 'updated' unless %w(updated newest views alpha).include?(@order)
      @show_up_for_review = can_edit? && !request.path.include?(up_for_review_path)

      articles = if request.path.include? up_for_review_path
                   Article.up_for_review(order: @order&.to_sym)
                 elsif @search_term.present?
                   Article.search(term: @search_term, category_id: @category&.id, order: @order&.to_sym)
                 elsif @category.present?
                   @category.articles_in_branch(order: @order&.to_sym)
                 else
                   Article.uncategorized(order: @order&.to_sym)
                 end

      @articles = paginate(articles)
    end

    def new
      @category             = Category.new
      @parent_category_code = params[:parent_category_code]
    end

    def edit
      return redirect_to root_path if @category.blank?
      @parent_category_code = @category.parent&.code
    end

    def create
      @category = Category.new(name: params[:name], parent: Category.find_by(code: params[:parent_category_code]))

      if @category.save
        flash[:green] = 'Category was created'
        redirect_to article_index_path(@category.code)
      else
        flash.now[:red]       = 'Category could not be created'
        @parent_category_code = params[:parent_category_code]
        render :new
      end
    end

    def update
      return redirect_to root_path if @category.blank?

      if @category.update(name: params[:name], parent: Category.find_by(code: params[:parent_category_code]))
        flash[:green] = 'Category was updated'
        redirect_to article_index_path(@category.code)
      else
        flash.now[:red]       = 'Category could not be updated'
        @parent_category_code = params[:parent_category_code]
        render :edit
      end
    end

    def destroy
      Category.find(params[:id].to_i).destroy!

      flash[:green] = 'Category was deleted'
      render json: {}, layout: false
    end

    private

    def fetch_category
      @category = Category.find_by(code: params[:cat_code].to_s.strip)
      @category = Category.find_by(id: params[:id].to_i) if @category.blank?
    end
  end
end

app/controllers/dokno/pagination_concern.rb
module Dokno
  module PaginationConcern
    extend ActiveSupport::Concern

    def paginate(records, max_per_page: 10)
      @page          = params[:page].to_i
      @total_records = records.size
      @total_pages   = (@total_records.to_f / max_per_page).ceil
      @total_pages   = 1 unless @total_pages.positive?
      @page          = 1 unless @page.positive? && @page <= @total_pages

      records.offset((@page - 1) * max_per_page).limit(max_per_page)
    end
  end
end

app/controllers/dokno/user_concern.rb
module Dokno
  module UserConcern
    extend ActiveSupport::Concern

    included do
      helper_method :user, :username, :can_edit?
    end

    def user
      # Attempt to eval the currently signed in 'user' object from the host app
      proc {
        $safe = 1
        eval sanitized_user_obj_string
      }.call

    rescue NameError => _e
      nil
    end

    def sanitized_user_obj_string
      Dokno.config.app_user_object.to_s.split(/\b/).first
    end

    def username
      user&.send(Dokno.config.app_user_name_method.to_sym).to_s
    end

    def can_edit?
      # Allow editing by default if host app user object is not configured
      return true  unless sanitized_user_obj_string.present?
      return false unless user&.respond_to? Dokno.config.app_user_auth_method.to_sym

      user.send(Dokno.config.app_user_auth_method.to_sym)
    end

    def authorize
      return redirect_to root_path unless can_edit?
    end
  end
end

app/helpers/dokno/application_helper.rb
module Dokno
  module ApplicationHelper
    def dokno_article_link(link_text = nil, slug: nil)
      return "Dokno article slug is required" unless slug.present?

      # Check for slug, including deprecated slugs
      article = Article.find_by(slug: slug.strip)
      article = ArticleSlug.find_by(slug: slug.strip)&.article if article.blank?

      return "Dokno article slug '#{slug}' not found" if article.blank?

      %Q(<a class="dokno-link" href="javascript:;" onclick="doknoOpenPanel('#{j article.slug}');">#{link_text.presence || article.title}</a>).html_safe
    end
  end
end

app/views/dokno/categories/_category_form.html.erb
<section class="mb-10">

  <div class="text-2xl mb-5 text-gray-500"><%= category.persisted? ? 'Edit' : 'New' %> Category</div>
  <hr class="mb-5" />

  <div class="mb-5">
    <div class="text-lg font-semibold"><label for="name">Category Name</label></div>
    <input type="text" name="name" id="name" value="<%= category.name %>" class="rounded text-xl shadow-inner bg-gray-100 p-2 mt-2 w-1/3" />
    <div class="text-gray-500 mt-2">Unique name for this category (required)</div>
  </div>

  <% if Dokno::Category.exists? %>
    <div class="mb-5 w-1/2">
      <div class="text-lg font-semibold"><label for="parent_category_code">Parent Category</label></div>

      <select name="parent_category_code" id="parent_category_code" size="1" class="rounded text-xl shadow-inner bg-gray-100 p-2 w-full max-w-full">
        <option value="">No Parent Category</option>

        <optgroup label="Categories">
          <% cache Dokno::Category do %>
            <%= Dokno::Category.select_option_markup.html_safe %>
          <% end %>
        </optgroup>
      </select>

      <div class="text-gray-500 mt-2">
        The existing category to which this category belongs.
        <% if (article_count = category.articles.count).positive? %>
          There <%= article_count > 1 ? "are #{article_count} articles" : 'is an article' %> currently in this category.
          Changing the parent category will move <%= article_count > 1 ? 'them' : 'it' %> as well.
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="mt-10">
    <button type="submit" class="bg-gray-700 text-gray-300 hover:bg-gray-900 hover:text-white rounded py-2 px-3 font-bold"><i data-feather="check" class="inline h-5"></i> SAVE CATEGORY</button>
    <% if category.persisted? %>
      <button type="button" class="bg-red-700 text-gray-300 hover:bg-red-900 hover:text-white rounded py-2 px-3 font-bold ml-5" onclick="deleteCategory('<%= category.id %>');"><i data-feather="trash" class="inline h-5"></i> DELETE</button>
    <% end %>
    <span class="text-lg ml-5"><a class="no-underline" href="<%= category.persisted? ? "#{dokno.article_index_path(category.code)}" : root_path %>">Cancel</a></span>
  </div>
</section>

<script>
  // Client-side select of cached select list
  selectOption('parent_category_code', '<%= j @parent_category_code %>');
  elem('input#name').focus();
</script>

app/views/dokno/categories/edit.html.erb
<%= form_with(model: @category, local: true) do |form| %>
  <% if @category.errors.any? %>
    <%= render 'partials/form_errors', errors: @category.errors %>
  <% end %>

  <%= render 'category_form', category: @category %>
<% end %>

app/views/dokno/categories/index.html.erb
<% if !current_page?(up_for_review_path) && (@category.blank? || @search_term.present?) %>
  <div class="text-center m-auto mb-10 w-full max-w-screen-xl">
    <% if @search_term.present? %>
      <div class="text-gray-600 text-2xl uppercase">
        <%= @total_records.positive? ? "#{@total_records} #{'article'.pluralize(@total_records)}" : 'No articles' %>
        found containing the search term
        <div class="text-4xl leading-tight"><span class="font-serif">&ldquo;</span> <%= @search_term %> <span class="font-serif">&rdquo;</span> </div>
      </div>
    <% else %>
      <div class="text-gray-600 text-2xl">
        Browse or search
        <% if (article_count = Dokno::Article.count) > 1 %>
          <%= number_with_delimiter(article_count, delimiter: ',') %> articles in
        <% end %>
        the
      </div>
      <div class="text-gray-800 text-4xl leading-tight uppercase"><%= Dokno.config.app_name %> knowledgebase</div>
    <% end %>
  </div>
<% end %>

<% if @category&.parent.present? %>
  <div class="text-gray-500 mb-5">
    <div><span class="text-gray-500 mr-1">Under</span> <%= @category.breadcrumb(search_term: @search_term, order: @order, hide_self: true) %></div>
  </div>
<% end %>

<% if !current_page?(up_for_review_path) && (Dokno::Category.exists? || Dokno::Article.exists?) %>
  <%= render 'partials/category_header' %>
<% end %>

<% if @articles.blank? %>

  <section class="border-t border-gray-300 py-10 text-xl">
    <% if Dokno::Category.exists? %>
      <% if @search_term.present? %>
        No articles found <% if @category.present? %>in this category<% end %> matching the given search criteria
      <% elsif @category.present? %>
        No articles found in this category
      <% else %>
        No uncategorized articles
      <% end %>
    <% elsif can_edit? %>
      <a href="<%= new_category_path(@category&.id) %>">Add your first category</a>
    <% end %>
  </section>

<% else %>

  <div id="dokno-article-list-controls-top" class="flex mb-10">
    <div class="w-2/3">
      <%= render 'partials/pagination' %>
    </div>
    <div class="w-1/3 text-right">
      <i data-feather="corner-right-down" class="h-5 inline-block" title="Sort order"></i>
      <a id="dokno-order-link-updated" class="ml-3 pb-1 <%= 'border-b-2 border-blue-900' if @order == 'updated' %>" href="?search_term=<%= CGI.escape @search_term.to_s %>&order=updated">Updated</a>
      <a id="dokno-order-link-newest" class="ml-3 pb-1 <%= 'border-b-2 border-blue-900' if @order == 'newest' %>" href="?search_term=<%= CGI.escape @search_term.to_s %>&order=newest">Newest</a>
      <a id="dokno-order-link-views" class="ml-3 pb-1 <%= 'border-b-2 border-blue-900' if @order == 'views' %>" href="?search_term=<%= CGI.escape @search_term.to_s %>&order=views">Views</a>
      <a id="dokno-order-link-alpha" class="ml-3 pb-1 <%= 'border-b-2 border-blue-900' if @order == 'alpha' %>" href="?search_term=<%= CGI.escape @search_term.to_s %>&order=alpha">Title</a>
    </div>
  </div>

  <div id="dokno-article-list">
    <% @articles.each do |article| %>
      <section class="border-t border-gray-300 py-10 text-xl flex">
        <div class="w-1/3 pr-10">
          <div class="flex">
            <div title="<%= 'Starred article' if article.starred %>" class="no-print w-10 text-gray-300"><i data-feather="<%= article.starred ? 'star' : 'chevron-right' %>" class="inline-block"></i></div>
            <div class="w-full">
              <a class="dokno-article-title <% unless article.active %>text-gray-500 italic<% end %>" href="<%= article_path article.slug %>?search_term=<%= @search_term %>&cat_code=<%= @category&.code %>&order=<%= @order %>" title="View article"><%= article.title %></a>
            </div>
          </div>
        </div>
        <div class="dokno-article-summary w-2/3 <% unless article.active %>text-gray-500 italic<% end %>">
          <div class="dokno-article-content-highlight mb-2"><%= article.summary.presence || 'No summary provided' %></div>

          <div class="text-base text-gray-500">
            <%= article.category_name_list(context_category_id: @category&.id, order: @order, search_term: @search_term) %>
          </div>

          <% unless @order == 'alpha' %>
            <div class="text-base">
              <% if @order == 'views' %>
                <div class="text-gray-500">This article was viewed <%= number_with_delimiter(article.views, delimiter: ',') %> <%= 'time'.pluralize(article.views) %></div>
              <% elsif @order == 'updated' %>
                <div class="text-gray-500">This article was last updated <%= time_ago_in_words article.updated_at %> ago</div>
              <% elsif @order == 'newest' %>
                <div class="text-gray-500">This article was added <%= time_ago_in_words article.created_at %> ago</div>
              <% end %>
            </div>
          <% end %>

          <% if !article.active %>
            <div class="bg-yellow-700 p-4 mt-5 rounded text-lg border-t-4 border-yellow-900 text-white font-base not-italic">
              <i data-feather="info" class="inline-block mr-1"></i> This article is no longer active
            </div>
          <% end %>

          <% if article.up_for_review? %>
            <div class="bg-<%= article.review_due_days.negative? ? 'red' : 'gray' %>-800 p-4 mt-5 rounded text-lg border-t-4 border-<%= article.review_due_days.negative? ? 'red' : 'gray' %>-900 text-white font-base not-italic">
              <i data-feather="bell" class="inline-block mr-1"></i> <%= article.review_due_days_string %>
            </div>
          <% end %>

        </div>
      </section>
    <% end %>
  </div>

  <div id="dokno-article-list-controls-bottom" class="flex mt-10">
    <div class="w-2/3">
      <%= render 'partials/pagination' %>
    </div>
    <div class="w-1/3 text-right"></div>
  </div>
<% end %>

<% if @search_term.present? && @articles.blank? %>
  <script> handleSearchHotKey(); </script>
<% end %>

app/views/dokno/categories/new.html.erb
<%= form_with(url: categories_path) do %>
  <% if @category.errors.any? %>
    <%= render 'partials/form_errors', errors: @category.errors %>
  <% end %>
  
  <%= render 'category_form', category: @category %>
<% end %>